<a href="https://colab.research.google.com/github/lizmutua/Demo-repo/blob/main/colabintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


***1 dimesion***

In [8]:
arr1 = np.array ({1,2,3,4,5,6,7,8,9})
arr1

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [13]:
arr1.shape

()

In [11]:
#2 dimention
arr2=np.array([[1,2,3],[1,2,3]])
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [14]:
arr2.shape

(2, 3)

In [12]:
#2 dimension

arr3=np.array([[1,2,3],[1,2,3],[1,2,3]])
arr3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
arr3.shape

(3, 3)

In [24]:
arr4=np.array([[[(1,2,3),(2,3,5),(7,8,10)], [(4,5,6),(7,8,9),(4,5,6)], [(5,6,7),(4,7,8),(3,4,6)]]])
arr4

array([[[[ 1,  2,  3],
         [ 2,  3,  5],
         [ 7,  8, 10]],

        [[ 4,  5,  6],
         [ 7,  8,  9],
         [ 4,  5,  6]],

        [[ 5,  6,  7],
         [ 4,  7,  8],
         [ 3,  4,  6]]]])

In [25]:
arr4.shape

(1, 3, 3, 3)

In [28]:
arr0 = np.zeros(7)
arr0

array([0., 0., 0., 0., 0., 0., 0.])

In [29]:
arr0.shape

(7,)

***arry with only ones ***

In [30]:
array6 = np.ones(2)
array6

array([1., 1.])

In [31]:
## Create an empty array with 2 elements
arry7= np.empty(2)
arry7

array([1., 1.])

In [32]:
#You can create an array with a range of elements:
arry8 = np.arange(5)
arry8

array([0, 1, 2, 3, 4])

In [34]:
#And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
arry9=np.arange(0,12,2)
arry9

array([ 0,  2,  4,  6,  8, 10])

In [39]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
arry10=np.linspace(0,15,5)
arry10

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [44]:
#Specifying your data type

#While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.
arry11=np.ones(3, dtype= np.int64)
arry11

array([1, 1, 1])

In [6]:
print('hello my name is Liz')

hello my name is Liz
